# Cerulean Plugin Configuration

# [ Cerulean Features ]
features:
  # The Player Logging feature sends messages when a player joins or leaves, if enabled.
  player-logging:
    enable: true
    # You can add color codes to join and leave messages using '&' and the color code. For example, yellow is '&e'.
    join-message: "&e%player% joined the game"
    quit-message: "&e%player% left the game"
  # **[THIS FEATURE IS NOT IMPLEMENTED YET]** The AFK feature tracks players' AFK status, if enabled.
  afk:
    enable: true
    # The AFK Timeout value defines how long to wait before marking a player as AFK in milliseconds.
    # By default, this is 60000l, for one minute.
    afk-timeout: 60000l
  # The Chat feature allows you to change the formatting of chat messages, if enabled.
  chat:
    enable: true
    chat-format: "%s: %s"

# [ Cerulean Commands ]
commands:
  # The Cerulean fly command. Players with the permission "cerulean.fly" will be able to toggle fly mode, if enabled.
  fly:
    enable: true
  # The Cerulean invsee command. Players with the permission "cerulean.invsee" will be able to view player inventories, if enabled.
  invsee:
    enable: true
  # The Cerulean damage command. Players with the permission "cerulean.damage" will be able to damage players via command, if enabled.
  damage:
    enable: true
  # The Cerulean short gamemode command. Players with the permisison "cerulean.gamemode" will be able to switch gamemodes of players with a the command "gm", if enabled.
  short-gamemode:
    enable: true