# Cerulean Plugin Configuration

# [ Cerulean Features ]
features:
  # The Player Logging feature sends messages when a player joins or leaves, if enabled.
  player-logging:
    enable: true
    # You can add color codes to join and leave messages using '&' and the color code. For example, yellow is '&e'.
    join-message: "&e%player% joined the game"
    quit-message: "&e%player% left the game"
  # The AFK feature tracks players' AFK status, if enabled.
  afk:
    enable: true
    # The AFK Timeout value defines how long to wait before marking a player as AFK in milliseconds.
    # By default, this is 60000l, for one minute.
    afk-timeout: 60000l

# [ Cerulean Commands ]
commands:
  # The Cerulean fly command. Players with the permission "cerulean.fly" will be able to use this, if enabled.
  fly:
    enable: true