name: Cerulean
version: '${project.version}'
main: me.itstotallyjan.cerulean.Cerulean
api-version: 1.19
authors: [ itstotallyjan ]
description: A useful, unbloated utility plugin.
softdepend: [ LuckPerms ]
commands: